FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS akshay
WORKDIR /Nop
RUN apt update && apt install unzip -y && mkdir /Nop/bin && mkdir /Nop/logs && unzip ./nopCommerce_4.50.3_NoSource_linux_x64.zip
EXPOSE 80
CMD ["/usr/bin/dotnet", "/Nop/Nop.Web.dll"]